name: "Check spelling"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: streetsidesoftware/cspell-action@c8855adc59d29c3fc73b5453b16717947c3f050c # v2.26.3
        with:
          files: |
            **/*.{md,slice}
